<a href="https://colab.research.google.com/github/LilyRosa/Matematica-Numerica-Google-Colab/blob/main/notebooks/tutoriales-generales/Numpy%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Creación de un array

In [2]:
x = np.array ( [1, 4, 3] )
x

array([1, 4, 3])

## Array multidimensional
Es expresado como una lista de listas que contienen las filas.

In [3]:
y = np.array ( [ [1, 4, 3],
                 [9, 2, 7] ] )
y

array([[1, 4, 3],
       [9, 2, 7]])

### Orden de la matriz

In [4]:
y.shape

(2, 3)

### Crear elementos en un cierto rango

In [5]:
z = np.arange (1, 2000, 1)
print (z)
type (z)

[   1    2    3 ... 1997 1998 1999]


numpy.ndarray

In [6]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

### Indexing

In [7]:
y [:, [0, 2] ] #Obtener las 2 primeras columnas

array([[1, 3],
       [9, 7]])

### Operaciones escalares con arrays

In [8]:
b = np.array ( [ [1, 2],
                 [3, 4] ] )

In [9]:
b + 2

array([[3, 4],
       [5, 6]])

In [10]:
b - 2

array([[-1,  0],
       [ 1,  2]])

In [11]:
b * 2

array([[2, 4],
       [6, 8]])

In [12]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [13]:
b ** 2

array([[ 1,  4],
       [ 9, 16]])

### Operaciones entre arrays

In [14]:
d = np.array ( [ [3, 4],
                 [5, 6] ] )

In [15]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [16]:
b - d

array([[-2, -2],
       [-2, -2]])

In [17]:
b * d

array([[ 3,  8],
       [15, 24]])

In [18]:
b / d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [19]:
b ** d

array([[   1,   16],
       [ 243, 4096]])

### Transposición

In [20]:
b.T

array([[1, 3],
       [2, 4]])

### Operaciones lógicas

In [21]:
b > 3

array([[False, False],
       [False,  True]])

In [22]:
b > d

array([[False, False],
       [False, False]])

### Indexado de un array de acuerdo a una condición

In [23]:
bmay3 = b [b > 3]
bmay3

array([4])

In [24]:
dmen5 = d [d < 5]
dmen5

array([3, 4])